### PR TITLE
[fix] https://github.com/duniter/duniter/issues/624:

### PR DESCRIPTION
**Pull request by M5oul**
- remove cesium folder before moving new one on it.

### CODE REVIEW

**Comment by M5oul** [comment]
Why this fail?
It's annoying.

**Comment by c-geek** [comment]
It will fail on Windows for sure. About Linux, maybe you need an `-f` for the `rm -rf`?

**Comment by c-geek** [comment]
> It will fail on Windows for sure.

Have you read this sentence?

**Comment by M5oul** [comment]
I didn't take it into account.
What could be done for Window?

**Comment by c-geek** [comment]
I don't know, that's why I did not use `rm -rf`. You should revert your code.

If you really want to change this code, a working solution would be to create a .js file that handles the different commands.

**Comment by M5oul** [comment]
Ok, I will revert it for now.
It won't be easy for me to do that JavaScript file. I could try.

**Comment by c-geek** [comment]
Yes, please try! That's a very good challenge.

**Pull request closed without merging**
